/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Layout: typeof import('./src/components/Layout/Layout.vue')['default']
    LayoutHeader: typeof import('./src/components/Layout/cnps/LayoutHeader.vue')['default']
    LayoutHeaderSearch: typeof import('./src/components/Layout/cnps/LayoutHeaderSearch.vue')['default']
    LayoutLeftMenu: typeof import('./src/components/Layout/cnps/LayoutLeftMenu.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NPopconfirm: typeof import('naive-ui')['NPopconfirm']
    NPopover: typeof import('naive-ui')['NPopover']
    NPopver: typeof import('naive-ui')['NPopver']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NScrollBar: typeof import('naive-ui')['NScrollBar']
    NSkeleton: typeof import('naive-ui')['NSkeleton']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTag: typeof import('naive-ui')['NTag']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
